"""empty message

Revision ID: 0b138cb93a9f
Revises: d2330c0370a7
Create Date: 2023-06-23 22:56:34.297751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b138cb93a9f'
down_revision = 'd2330c0370a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
